run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - zkmultiswap/gnark-tests

linters:
  enable:
    - errcheck
    - goimports
    - golint
    - govet
    - staticcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - ineffassign
      text: "ineffectual assignment to"