// Package proof range proof
// Variant of Lipmaa’s Compact Argument for Positivity proposed by Geoffroy Couteau et al. for range proof
// To prove an integer x lies in the range [a, b], we can show that x - a and b - x are positive by decomposing
// them as sum of four squares
// Paper: Removing the Strong RSA Assumption from Arguments over the Integers
// Link: https://eprint.iacr.org/2016/128
package proof

import (
	"bytes"
	"crypto"
	"crypto/sha256"
	"math/big"
)

const (
	rpChallengeStatement = "c = (g^x)(h^r), x is non-negative"
	sha256Len            = 32
	commitLen            = sha256Len * 5
)

var rpB = big.NewInt(4096) // bound B

// RangeProof is the proof for range proof
type RangeProof struct {
	// c = (g^x)(h^r)
	c *big.Int
	// commitment of x,
	// containing c1, c2, c3, c4, ci = (g^xi)(h^ri),
	// x = x1^2 + x2^2 + x3^2
	commitX Int3
	// the commitment delta
	commitment rpCommitment
	// the response to the challenge
	response *rpResponse
}

// NewRangeProof generates a new proof for range proof
func NewRangeProof(c *big.Int, commitX Int3, commitment rpCommitment, response *rpResponse) *RangeProof {
	return &RangeProof{
		c:          c,
		commitX:    commitX,
		commitment: commitment,
		response:   response,
	}
}

// rpCommitment is the range proof commitment generated by the prover
type rpCommitment [commitLen]byte

// rpChallenge is the challenge for range proof
type rpChallenge struct {
	statement string   // the statement for the challenge
	g, h, n   *big.Int // public parameters: G, H, N
	a, b      *big.Int // the range [a, b]
	c3        Int3     // commitment of x containing c1, c2, c3
}

// newRPChallenge generates a new challenge for range proof
func newRPChallenge(pp *PublicParameters, a, b *big.Int, c3 Int3) *rpChallenge {
	return &rpChallenge{
		statement: rpChallengeStatement,
		g:         pp.G,
		h:         pp.H,
		n:         pp.N,
		a:         a,
		b:         b,
		c3:        c3,
	}
}

// Serialize generates the serialized data for range proof challenge in byte format
func (r *rpChallenge) serialize() []byte {
	var buf bytes.Buffer
	buf.WriteString(r.statement)
	buf.WriteString(r.g.String())
	buf.WriteString(r.h.String())
	buf.WriteString(r.n.String())
	buf.WriteString(r.a.String())
	buf.WriteString(r.b.String())
	for _, c := range r.c3 {
		buf.WriteString(c.String())
	}
	return buf.Bytes()
}

// sha256 generates the SHA256 hash of the range proof challenge
func (r *rpChallenge) sha256() []byte {
	hashF := crypto.SHA256.New()
	hashF.Write(r.serialize())
	hashResult := hashF.Sum(nil)
	return hashResult
}

// bigInt serializes the range proof challenge to bytes, generates the SHA256 hash of the byte data,
// and convert the hash to big integer
func (r *rpChallenge) bigInt() *big.Int {
	hashVal := r.sha256()
	return new(big.Int).SetBytes(hashVal)
}

// rpResponse is the response sent by the prover after receiving verifier's challenge
type rpResponse struct {
	Z4  Int4
	T4  Int4
	TAU *big.Int
}

// newRPCommitment generates a new commitment for range proof
func newRPCommitment(d4 Int4, d *big.Int) rpCommitment {
	var dByteList [4][]byte
	for i := 0; i < 4; i++ {
		dByteList[i] = d4[i].Bytes()
	}
	dBytes := d.Bytes()
	hashF := crypto.SHA256.New()
	var sha256List [4][]byte
	for i, dByte := range dByteList {
		hashF.Write(dByte)
		sha256List[i] = hashF.Sum(nil)
		hashF.Reset()
	}
	var commitment rpCommitment
	for idx, s := range sha256List {
		copy(commitment[idx*sha256Len:(idx+1)*sha256Len], s)
	}
	hashF.Write(dBytes)
	copy(commitment[commitLen-sha256Len:], hashF.Sum(nil))
	return commitment
}

// RPProver refers to the Prover in zero-knowledge integer range proof
type RPProver struct {
	pp *PublicParameters // public parameters
	//x         *big.Int          // x, non-negative integer
	r         *big.Int // r
	sp        *big.Int // security parameter, kappa
	C         *big.Int // c = (g^x)(h^r)
	a, b      *big.Int // a, b, range [a, b]
	x0, r0    *big.Int // x0 = (b-x), r0 = r
	ca        *big.Int // ca = (c * g^(-a))^4 mod n
	squareX3  Int3     // three square sum of 4(b-x)(x-a) + 1 = x1^2 + x2^2 + x3^2
	commitFSX Int3     // commitment of four square of x: c1, c2, c3, ci = (g^xi)(h^ri)
	randM4    Int4     // random coins: m0, m1, m2, m3, mi is in [0, 2^(B + 2kappa)]
	randR3    Int3     // random coins: r1, r2, r3, ri is in [0, n]
	randS4    Int4     // random coins: s0, s1, s2, s3, si is in [0, 2^(2kappa)*n]
	sigma     *big.Int // random selected parameter sigma in [0, 2^(B + 2kappa)*n]
}

// NewRPProver generates a new range proof prover
func NewRPProver(pp *PublicParameters, r, a, b *big.Int) *RPProver {
	prover := &RPProver{
		pp: pp,
		r:  r,
		a:  a,
		b:  b,
		sp: big.NewInt(securityParam),
	}
	//prover.x = new(big.Int).Sub(b, a)
	//prover.calC()
	return prover
}

// calculate parameter Ca, Ca = (c * g^(-a))^4 mod n
func (r *RPProver) calCa() {
	opt := new(big.Int).Neg(r.a)
	defer iPool.Put(opt)
	r.ca = new(big.Int).Exp(r.pp.G, opt, r.pp.N)
	r.ca.Mul(r.ca, r.C)
	r.ca.Exp(r.ca, big4, r.pp.N)
}

// calculate parameter c, c = (g^x)(h^r)
func (r *RPProver) calC(x *big.Int) *big.Int {
	r.C = new(big.Int).Exp(r.pp.G, x, r.pp.N)
	opt := iPool.Get().(*big.Int)
	defer iPool.Put(opt)
	r.C.Mul(r.C, opt.Exp(r.pp.H, r.r, r.pp.N))
	r.C.Mod(r.C, r.pp.N)
	return r.C
}

// Prove generates the proof for range proof
func (r *RPProver) Prove(x *big.Int) (*RangeProof, error) {
	r.calC(x)
	r.calCa()
	r.x0 = new(big.Int).Sub(r.b, x)
	r.r0 = new(big.Int).Set(r.r)
	cx, err := r.commitForX(x)
	if err != nil {
		return nil, err
	}
	commitment, err := r.commit()
	if err != nil {
		return nil, err
	}
	response, err := r.response()
	if err != nil {
		return nil, err
	}
	return NewRangeProof(r.C, cx, commitment, response), nil
}

// commitForX generates the commitment for x
func (r *RPProver) commitForX(x *big.Int) (Int3, error) {
	// calculate three squares that 4(b-x)(x-a) + 1 = x1^2 + x2^2 + x3^2
	target := iPool.Get().(*big.Int).Sub(r.b, x)
	defer iPool.Put(target)
	opt := iPool.Get().(*big.Int).Sub(x, r.a)
	defer iPool.Put(opt)
	target.Mul(target, opt)
	target.Lsh(target, 2)
	target.Add(target, big1)
	ts, err := ThreeSquares(target)
	if err != nil {
		return Int3{}, err
	}
	r.squareX3 = ts
	// calculate commitment for x
	var rc Int3
	if rc, err = newThreeRandCoins(r.pp.N); err != nil {
		return Int3{}, err
	}
	r.randR3 = rc
	c3 := newRPCommitFromFS(r.pp, rc, ts)
	r.commitFSX = c3
	return c3, nil
}

// newRPCommitFromFS generates a range proof commitment for a given integer
func newRPCommitFromFS(pp *PublicParameters, coins Int3, ts Int3) (cList Int3) {
	opt := iPool.Get().(*big.Int)
	defer iPool.Put(opt)
	for i := 0; i < int3Len; i++ {
		cList[i] = new(big.Int).Exp(pp.G, ts[i], pp.N)
		cList[i].Mul(cList[i], opt.Exp(pp.H, coins[i], pp.N))
	}
	return
}

// commit composes the commitment for range proof
func (r *RPProver) commit() (rpCommitment, error) {
	// pick m0, m1, m2, m3, mi is in [0, 2^(B + 2kappa)]
	powMLmt := iPool.Get().(*big.Int).Set(r.sp)
	defer iPool.Put(powMLmt)
	powMLmt.Lsh(powMLmt, 1)
	powMLmt.Add(powMLmt, rpB)
	mLmt := iPool.Get().(*big.Int).Exp(big2, powMLmt, nil)
	defer iPool.Put(mLmt)
	m4, err := newFourRandCoins(mLmt)
	if err != nil {
		return rpCommitment{}, err
	}
	r.randM4 = m4
	// pick s0, s1, s2, s3, si is in [0, 2^(2kappa)*n]
	sLmt := iPool.Get().(*big.Int).Exp(big4, r.sp, nil)
	defer iPool.Put(sLmt)
	sLmt.Mul(sLmt, r.pp.N)
	var s4 Int4
	if s4, err = newFourRandCoins(sLmt); err != nil {
		return rpCommitment{}, err
	}
	r.randS4 = s4
	// pick sigma in [0, 2^(B + 2kappa)*n]
	sLmt.Lsh(sLmt, uint(rpB.Int64()))
	var sigma *big.Int
	if sigma, err = freshRandCoin(sLmt); err != nil {
		return rpCommitment{}, err
	}
	r.sigma = sigma
	// calculate commitment
	d4 := r.firstPartH(m4, s4)
	d := r.secondPartH(m4)
	c := newRPCommitment(d4, d)
	return c, nil
}

// firstPartH calculates h0, h1, h2, h3, hi = (g^mi)(h^si) mod n
func (r *RPProver) firstPartH(m, s Int4) Int4 {
	var h4 Int4
	opt := iPool.Get().(*big.Int)
	defer iPool.Put(opt)
	for i := 0; i < int4Len; i++ {
		h := new(big.Int).Set(r.pp.G)
		h.Exp(h, m[i], r.pp.N)
		h.Mul(h, opt.Exp(r.pp.H, s[i], r.pp.N))
		h4[i] = h.Mod(h, r.pp.N)
	}
	return h4
}

// secondPartH calculates h = (h^(sigma))*(c^(m0)_a)*(product of (ci^(-mi))) mod n
func (r *RPProver) secondPartH(m Int4) *big.Int {
	// prefix = h^sigma * c_a^m_0
	prefix := iPool.Get().(*big.Int).Exp(r.pp.H, r.sigma, r.pp.N)
	defer iPool.Put(prefix)
	opt := iPool.Get().(*big.Int)
	defer iPool.Put(opt)
	opt.Exp(r.ca, r.randM4[0], r.pp.N)
	prefix.Mul(prefix, opt)
	prefix.Mod(prefix, r.pp.N)
	// ci^(-mi)
	var cPowM3 Int3
	negM := iPool.Get().(*big.Int)
	defer iPool.Put(negM)
	// product of ci^(-mi) mod n, for i = 1, 2, 3
	for i := 0; i < int3Len; i++ {
		cPowM3[i] = opt.Exp(r.commitFSX[i], negM.Neg(m[i+1]), r.pp.N)
	}
	// product of ci^(-mi)
	// TODO: refactor
	d := big.NewInt(1)
	for i := 0; i < int3Len; i++ {
		d.Mul(d, cPowM3[i])
		d.Mod(d, r.pp.N)
	}
	d.Mul(d, prefix)
	d.Mod(d, r.pp.N)
	return d
}

// calChallengeBigInt calculates the challenge for range proof in big integer format
func (r *RPProver) calChallengeBigInt() *big.Int {
	challenge := newRPChallenge(r.pp, r.a, r.b, r.commitFSX)
	return challenge.bigInt()
}

// response generates the response for verifier's challenge
func (r *RPProver) response() (*rpResponse, error) {
	c := r.calChallengeBigInt()
	// zi = e * xi + mi, for i = 0, 1, 2, 3
	var z4 Int4
	z4[0] = new(big.Int).Mul(c, r.x0)
	z4[0].Add(z4[0], r.randM4[0])
	for i := 0; i < int3Len; i++ {
		z4[i+1] = new(big.Int).Mul(c, r.squareX3[i])
		z4[i+1].Add(z4[i], r.randM4[i+1])
	}
	// ti = e * ri + si, for i = 0, 1, 2, 3
	var t4 Int4
	t4[0] = new(big.Int).Mul(c, r.r0)
	t4[0].Add(t4[0], r.randS4[0])
	for i := 0; i < int3Len; i++ {
		t4[i+1] = new(big.Int).Mul(c, r.randR3[i])
		t4[i+1].Add(t4[i+1], r.randS4[i+1])
	}

	// tau = sigma + e * (x0 * r0 - product of xi * ri, for i = 1, 2, 3)
	sumXR := iPool.Get().(*big.Int)
	defer iPool.Put(sumXR)
	sumXR.SetInt64(0)
	opt := iPool.Get().(*big.Int)
	defer iPool.Put(opt)
	for i := 0; i < int3Len; i++ {
		sumXR.Add(sumXR, opt.Mul(r.squareX3[i], r.randR3[i]))
	}
	//t := new(big.Int).Sub(r.r, sumXR)
	//t.Mul(t, c)
	//t.Add(t, r.sigma)
	tau := new(big.Int).Mul(r.x0, r.r0)
	tau.Sub(tau, sumXR)
	tau.Mul(tau, c)
	tau.Add(tau, r.sigma)
	response := &rpResponse{
		Z4:  z4,
		T4:  t4,
		TAU: tau,
	}
	return response, nil
}

// RPVerifier refers to the Verifier in zero-knowledge integer range proof
type RPVerifier struct {
	pp         *PublicParameters // public parameters
	sp         *big.Int          // security parameters
	C          *big.Int          // C, (g^x)(h^r)
	a, b       *big.Int          // the range [a, b]
	commitment rpCommitment      // commitment, delta = H(d1, d2, d3, d4, d)
	commitFSX  Int3
	c0         *big.Int // c0 = c^(-1)*g^b mod n
	ca         *big.Int // ca = (c*g(-a))^4 mod n
}

// NewRPVerifier generates a new range proof verifier
func NewRPVerifier(pp *PublicParameters, a, b *big.Int) *RPVerifier {
	verifier := &RPVerifier{
		pp: pp,
		sp: big.NewInt(securityParam),
		a:  a,
		b:  b,
	}
	return verifier
}

// Verify verifies the range proof
func (r *RPVerifier) Verify(proof *RangeProof) bool {
	r.SetC(proof.c)
	opt := iPool.Get().(*big.Int).Neg(big1)
	defer iPool.Put(opt)
	r.c0 = new(big.Int).Exp(r.C, opt, r.pp.N)
	opt.Exp(r.pp.G, r.b, r.pp.N)
	r.c0.Mul(r.c0, opt)
	r.c0.Mod(r.c0, r.pp.N)
	opt.Neg(r.a)
	opt.Exp(r.pp.G, opt, r.pp.N)
	r.ca = new(big.Int).Mul(r.C, opt)
	r.ca.Mod(r.ca, r.pp.N)
	r.ca.Exp(r.ca, big4, r.pp.N)
	r.setCommitForX(proof.commitX)
	r.setCommitment(proof.commitment)
	return r.VerifyResponse(proof.response)
}

// SetC sets C to the verifier
func (r *RPVerifier) SetC(c *big.Int) {
	r.C = c
}

// setCommitment sets the commitment to the verifier
func (r *RPVerifier) setCommitment(c rpCommitment) {
	r.commitment = c
}

// setCommitForX sets the commitment of x to the verifier
// Commitment of x: c1, c2, c3, ci = (g^x1=i)(h^ri)
func (r *RPVerifier) setCommitForX(c3 Int3) {
	r.commitFSX = c3
}

// challenge generates a challenge for prover's commitment
func (r *RPVerifier) challenge() *big.Int {
	challenge := newRPChallenge(r.pp, r.a, r.b, r.commitFSX)
	return challenge.bigInt()
}

// VerifyResponse verifies the response, if accepts, return true; otherwise, return false
func (r *RPVerifier) VerifyResponse(response *rpResponse) bool {
	c := r.challenge()
	// the first 4 parameters: (g^zi)(h^ti)(ci^(-e)) mod n
	var firstFourParams Int4
	negC := iPool.Get().(*big.Int).Neg(c)
	defer iPool.Put(negC)
	opt := iPool.Get().(*big.Int)
	defer iPool.Put(opt)
	firstFourParams[0] = new(big.Int).Exp(r.pp.G, response.Z4[0], r.pp.N)
	firstFourParams[0].Mul(
		firstFourParams[0],
		opt.Exp(r.pp.H, response.T4[0], r.pp.N),
	)
	firstFourParams[0].Mul(
		firstFourParams[0],
		opt.Exp(r.c0, negC, r.pp.N),
	)
	for i := 1; i < int4Len; i++ {
		firstFourParams[i] = new(big.Int).Exp(r.pp.G, response.Z4[i], r.pp.N)
		firstFourParams[i].Mul(
			firstFourParams[i],
			opt.Exp(r.pp.H, response.T4[i], r.pp.N),
		)
		firstFourParams[i].Mul(
			firstFourParams[i],
			opt.Exp(r.commitFSX[i-1], negC, r.pp.N),
		)
		firstFourParams[i].Mod(firstFourParams[i], r.pp.N)
	}

	//cPowNegE := iPool.Get().(*big.Int)
	//defer iPool.Put(cPowNegE)
	//cPowNegE.Exp(r.C, negC, r.pp.N) // c^(-e)
	//hPowT := iPool.Get().(*big.Int)
	//defer iPool.Put(hPowT)
	//hPowT.Exp(r.pp.H, response.T, r.pp.N) // h^t
	// prefix = h^tau * g^e * c_a^z_0 mod n
	prefix := new(big.Int).Exp(r.pp.H, response.TAU, r.pp.N)
	defer iPool.Put(prefix)
	prefix.Mul(prefix, opt.Exp(r.pp.G, c, r.pp.N))
	prefix.Mod(prefix, r.pp.N)
	prefix.Mul(prefix, opt.Exp(r.ca, response.Z4[0], r.pp.N))
	prefix.Mod(prefix, r.pp.N)
	//product of (ci^zi)(h^t)(c^(-e)) mod n
	prodParam := iPool.Get().(*big.Int).SetInt64(1)
	defer iPool.Put(prodParam)
	for i := 0; i < int3Len; i++ {
		opt.Neg(response.Z4[i+1])
		prodParam.Mul(
			prodParam,
			opt.Exp(r.commitFSX[i], opt, r.pp.N),
		)
		prodParam.Mod(prodParam, r.pp.N)
	}
	prodParam.Mul(prefix, prodParam)
	prodParam.Mod(prodParam, r.pp.N)
	//prodParam.Mul(prodParam, hPowT)
	//prodParam.Mod(prodParam, r.pp.N)
	//prodParam.Mul(prodParam, cPowNegE)
	//prodParam.Mod(prodParam, r.pp.N)

	hashF := sha256.New()
	var sha256List [4][]byte
	for i := 0; i < 4; i++ {
		hashF.Write(firstFourParams[i].Bytes())
		sha256List[i] = hashF.Sum(nil)
		hashF.Reset()
	}
	hashF.Write(prodParam.Bytes())
	h := hashF.Sum(nil)
	var commitment rpCommitment
	for i := 0; i < 4; i++ {
		copy(commitment[i*sha256Len:(i+1)*sha256Len], sha256List[i])
	}
	copy(commitment[commitLen-sha256Len:], h)
	return commitment == r.commitment
}
